package lemonade.enumeration;

public enum UpgradeType {
    HIGH_OUTPUT_CITRUS_JUICER(),
    SHADE_MAKER_3000_CANOPY(),
    MIRACLE_9000_POWER_JUICER(),
    EZSERVE_CASH_REGISTER(),
    MR_FRIDGE(),
    ICE_O_MATIC_ICE_DISPENSER(),
    CLASSIC_STAND(),
    HIGH_FIVE_SOUND_SYSTEM(),
    LEMON_STAND(),
    BRIGHT_LIGHTS_NEON_SYSTEM(),
    TAKE2_LEMONADE_DISPENSER(),
    HIGH_OUTPUT_AUTOMATIC_ICE_MAKER(),
    CASTLE_STAND(),
    MAX_UPGRADE_TYPE();
}
